config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/', to: 'pages#home'
  get '/about', to: 'pages#about', as: 'about'

  get '/users', to: 'users#index', as: 'users'
  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#eidt', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  put '/user/:id', to: 'users#delete_photo', as: 'delete_photo'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'


  get '/cards', to: 'cards#index', as: 'cards'
  get '/cards', to: 'cards#new'
  post '/cards', to: 'cards#create', as: 'new_card'
  get '/cards/:id', to: 'cards#show', as: 'card'
  get '/cards/:id/edit', to: 'cards#edit', as: 'edit_card'
  patch '/cards/:id', to:'cards#update', as: 'patch_card'
  delete '/cards/:id', to: 'cards#destroy', as: 'delete_card'

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  has_many :card_skills
  has_many :skills, through: :card_skills
end

app/models/card_skill.rb
class CardSkill < ActiveRecord::Base
  belongs_to :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :user_skills
	has_many :users, through: :user_skills

	has_many :card_skills
	has_many :cards, through: :card_skills
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :cards
	has_many :user_skills
	has_many :skills, through: :user_skills

	has_attached_file :image, styles: { medium: "300x300", thumb: "125x125" }, default_url: "/assets/default.png"

	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	# Data validations
	validates :first, :last, :email, presence: true, length: {maximum: 255}
	validates :password, length: { minimum: 3, message: "must be at least 3 characters" }, allow_nil: true
	validates :email, uniqueness: true, format: { with: /@/, message: "must be a valid Eamil address" }, length: { minimum: 6 }

	def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include SkillsHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index
		@cards = Card.all.order("created_at DESC")
	end

	def new
		@card = Card.new
	end

	def create
		@card = Card.create(card_params)
		if @card.save
			flash[:notice] = "successfully created new card!"
			redirect_to user_path(current_user)
		else
			flash[:notice] = "something went wrong :'("
			redirect_to '/'
		end
	end

	def show
		@card = get_card
	end

	def edit
		@card = get_card
		render :partial => "editCard"
	end

	def update
		@card = get_card
		@card.update_attributes(card_params)
		flash[:notice] = "card updated"
		redirect_to user_path(current_user)
	end

	def destroy
		@card = get_card
		@card.destroy
		flash[:notice] = "Deleted card"
		redirect_to user_path(current_user)
	end

	private

	def get_card
		Card.find_by_id(params[:id]) 
	end

	def card_params
		params.require(:card).permit(:family, :title, :working_on, :user_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@cards = Card.all.order('created_at DESC')
  	@user = User.all
  	@card = Card.new()
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :no_double_login, only: [:new]

	def new
		@user = User.new
	end

	def create
		user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notie] = "Successfully logged in"
      redirect_to @user
    else
    	flash[:notice] = "Invalid Email or Password"
      redirect_to login_path
    end
	end

	def destroy
		logout
		flash[:notice] = " Successfully logged out"
		redirect_to root_path
	end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	def index
		@skills = Skill.all
	end

	def new
		@skill = Skill.new
	end

	def create
		@skill = Skill.new(skill_params)
		if @skill.save
			flash[:notice] = "Skill saved"
		else
			flash[:notice] = "Something went wrong"
		end
		redirect_to user_path(current_user)
	end

	def show
		@skill = Skill.find_by_id(params[:id])
	end

	def edit
		@skill = Skill.find_by_id(params[:id])
	end

	def update
		@skill = Skill.find_by_id(params[:id])
		@skill.update_attributes(skill_params)
		flash[:notice] = "Successfully updated skills"
		redirect_to user_path(current_user)
	end

	def destroy
		@skill = Skill.find_by_id(params[:id])
		@skill.destroy
		flash[:notice] = "Successfully deleted skill"
		redirect_to user_path(current_user)
	end

	private

	def skill_params
		params.require(:skill).permit(:skill)
	end
		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :no_double_login, only: [:new]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		login(@user)
		redirect_to @user
	end

	def show
		@user = User.find_by_id(params[:id])
		if @user.id != current_user.id
			redirect_to user_path(current_user)
		end
		@cards = @user.cards.order("created_at DESC")
		@card = Card.find_by_id(params[:card_id]) || Card.new()
	end

	# do you do anything?
	def find_card
		@card = Card.find(:card)
	end

	def edit
		@user = User.find_by_id(params[:id])	
	end

	def update
		@user = User.find_by_id(params[:id])
		@user.update_attributes(update_user_params)
		flash[:notice] = "User Profile updated successfully"
		redirect_to user_path(@user.id)
	end

	def delete_photo
		@user = User.find_by_id(params[:id])
		@user.image = nil 
		@user.save
		redirect_to user_path(@user.id)
	end

	def destroy
	end

	private

	def user_params
		params.require(:user).permit(:first,:last,:email,:password)
	end

	def update_user_params
		params.require(:user).permit(:first, :last, :email, :program, :cohort, :current_title, :image, :city, :state)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def no_double_login
    if current_user
      redirect_to root_path
    end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
	def drop_down
		selections = []
		Skill.all.each do |skill|
			selections << [skill.name, skill]
		end
		return selections
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_editCard.html.erb
<%= form_for @card, :url => patch_card_path, :html => { :method => :patch } do |f| %>
    <% if @card.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@card.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @card.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

<div class="panel panel-default">
    <div class="panel-body">
        <%= f.label :family %>
        <br>
        <%= f.select :family, [['Project', 'project'], ['Skill Share', 'skill_share'], ['Networking','networking']] %>
        <br>
        <strong>Card Title:</strong> 
        <br>
        <%= f.text_field :title, class: "form-control" %>
        <strong>Card description:</strong>
        <br>
        <%= f.text_area :working_on, class: "form-control" %>
        <%= f.hidden_field :user_id, value: current_user.id%>
        
    </div>
    <div class="panel-footer">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/cards/_newCard.html.erb
<%= form_for @card, :url => new_card_path, :html => {:method => :post } do |f| %>
    <% if @card.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@card.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @card.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

<div class="panel panel-default">
    <div class="panel-body">
        <%= f.label :family %>
        <br>
        <%= f.select :family, [['Project', 'project'], ['Skill Share', 'skill_share'], ['Networking','networking']] %>
        <br>
        <strong>Card Title:</strong> 
        <br>
        <%= f.text_field :title, placeholder: "Developer looking for UX Designer", class: "form-control" %>
        <strong>Card description:</strong>
        <br>
        <%= f.text_area :working_on, placeholder: "Need wireframes", class: "form-control" %>
        <%= f.hidden_field :user_id, value: current_user.id%>
    </div>
    <div class="panel-footer">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
    </div>

app/views/cards/show.html.erb
<div class="container">
	<div class="card <%= @card.family %>">
		<h5 class="flag flag-<%= @card.family %> pull-right">
			<% if @card.family == "skill_share" %>
				SKILL SHARE
			<% else %>
				<%= @card.family.upcase %>
			<% end %>
		</h5>
		<h5 class="title"><%= @card.title.upcase %> </h5>
		<hr>
		<p class="location pull-right"><span class="glyphicon glyphicon-map-marker"></span> <%= @card.user.city.upcase %>, <%= @card.user.state.upcase %></p>
		<p class="name"><%= @card.user.first.upcase %> <%= @card.user.last.upcase %></p>
		<p class="current-position"> <%= @card.user.current_title %></p>
		<hr>
		<br>
		<p class="working_on"><strong>Description: </strong> <%= @card.working_on %> </p>
		<div class="centered">
			<%= link_to "mailto:#{@card.user.email}", class: 'btn btn-primary btn-email btn-filter', target: '_blank' do %> <i class="glyphicon glyphicon-envelope"></i> CONTACT ME<% end %>
			<%= link_to root_path, class: 'btn btn-danger btn-back btn-filter' do %> BACK<% end %>
		</div>
	</div>
	<div class="profile-time">Created <%= time_ago_in_words(@card.created_at).gsub('about','') %> ago</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GA Extend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- viewport basics -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- fonts -->
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>
<!-- navbar -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/"> <%= image_tag("gax_logo_sm.png", :class => "navIcon") %>
          
        </a>
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path, class: "navbar-link" %>
          <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user), id: "user_link", class: "navbar-link"  %></li>
            <li><%= link_to "Logout", logout_path, id: "logout_link", class: "navbar-link"  %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path, id: "signup_link" %></li>
            <li><%= link_to "Login", login_path, id: "login_link" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- flash notices -->
    <% flash.each do |name, msg| %>
    <% if name == "error" %>
      <p class="alert-danger centered">
    <% else %>
      <p class="alert-success centered">
    <% end %>
      <small> <%= name.capitalize %>: <%= msg %> </small>
    </p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<p class="about_title">About GA Extend</p>
		<p class="about_text">As recent General Assembly grads, we want to create a space where we can <strong>collaborate with other alumni, share skills, sustain connections and grow our networks.</strong>  While GA provides post-program Outcomes support and alumni events, there was no central place for us to connect directly - until now. </p>

		<p class="about_text"> GA Extend promotes <strong>productive engagement</strong> - work with other alumni to develop and maximize your GA learning and broaden your skill set to give yourself a competitive advantage in job searching, interviews and networking.  It works!</p>

		<p class="about_text"> Whether you are a developer looking for a designer for your next app idea or a PM seeking to expand your alumni network, why not <strong>leverage and extend your GA experience</strong> here with us?</p>

		<p class="about_text">Check out the most recent alumni postings <a href="/">here!</a> </p>
	</div>
</div>

<div class="container centered devs8">
	<div class="row"> 
		<div class="col-md-6 col-md-offset-3 container">
			<p class="about_title ">Developers:</p>
			<div class="col-md-6 about_profile">
				<%= image_tag("danny.jpg", size: "75x75", class: 'about_photo') %>
				<p class="about_title">Danny Chan</p>
				<div class="row links">
					<div class="col-xs-2 col-xs-offset-3">
						<a href="https://www.linkedin.com/in/chandanny516"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
					</div>
					<div class="col-xs-2">
						<a href="https://github.com/chan-d"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
					</div>
					<div class="col-xs-2">
						<a href="http://dannychan.info"><i class="fa fa-laptop fa-2x" aria-hidden="true"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-6 about_profile">
				<%= image_tag("joe.jpg", size: "75x75", class: 'about_photo') %>
				<p class="about_title">Joe Roers</p>
				<div class="row links">
					<div class="col-xs-2 col-xs-offset-3">
						<a href="https://www.linkedin.com/in/joeroers"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
					</div>
					<div class="col-xs-2">
						<a href="https://github.com/jroers"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
					</div>
					<div class="col-xs-2">
						<a href="http://joeroers.com"><i class="fa fa-laptop fa-2x" aria-hidden="true"></i></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<br>
<div class="container centered designer">
	<div class="col-md-6 col-md-offset-3">
		<p class="about_title ">Designer:</p>

		<div class="col-md-6 col-md-offset-3 about_profile">
			<%= image_tag("malcolm.jpg", size: "75x75", class: 'about_photo') %>
			<p class="about_title">Malcolm McCarry</p>
			<div class="row links">
				<div class="col-xs-12">
					<a href="https://www.linkedin.com/in/malcolmmccarry"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
	</div>
</div>
<br>
<div class="container centered product-managers">
	<p class="about_title">Product Managers:</p>
	<div class="col-md-10 col-md-offset-1 centered" >
		<div class="col-md-4">
			<%= image_tag("miranda.jpg", size: "75x75", class: 'about_photo') %>
			<p class="about_title">Miranda Ko</p>
			<div class="row links">
				<div class="col-xs-12">
					<a href="https://www.linkedin.com/in/mirandayko"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<%= image_tag("patricia.jpg", size: "75x75", class: 'about_photo') %>
			<p class="about_title">Patricia Montoya</p>
			<div class="row links">
				<div class="col-xs-12">
					<a href="https://www.linkedin.com/in/montoyapatricia"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<%= image_tag("sebastian.jpg", size: "75x75", class: 'about_photo') %>
			<p class="about_title">Sebastian Duran</p>
			<div class="row links">
				<div class="col-xs-12">
					<a href="https://www.linkedin.com/in/sebduran"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron centered"> <p class="jumbo_text"> Connect with alumni, develop your skills and
<br>extend your GA experience</p></div>

<div class='container buttons'> <div class="button_label">FILTER BY TAG:</div> 
	<div class='col-md-12 centered'>
		<%= link_to 'SKILL SHARE', '/', class:'btn btn-warning btn-filter btn-skill-share' %> 
		<%= link_to 'PROJECTS', '/', class:'btn btn-success btn-filter btn-project' %> 
		<%= link_to 'NETWORKING', '/', class:'btn btn-danger btn-filter btn-networking' %> 
		<%= link_to 'SHOW ALL', '/', class:'btn btn-secondary btn-filter btn-all' %> 
	</div>
</div>

<div class="container">
	<div class="row cards"> 
		<% @cards.each do |card| %>
			<div class="container col-md-4 col-sm-6 col-xs-12 <%= card.family %>">
				<div class="card <%= card.family %>">
					<h5 class="flag flag-<%= card.family %> pull-right">
						<% if card.family == "skill_share" %>
							SKILL SHARE
						<% else %>
							<%= card.family.upcase %>
						<% end %>
					</h5>
					<h5 class="title"><%= link_to "#{card.title.upcase}", {:controller => "cards", :action => "show", :id => card.id} %> </h5>
					<hr>
					<p class="location pull-right"><span class="glyphicon glyphicon-map-marker"></span> <%= card.user.city.upcase %>, <%= card.user.state.upcase %></p>
					<p class="name"><%= card.user.first.upcase %> <%= card.user.last.upcase %></p>
					<p class="current-position"><%= card.user.current_title %></p>
							<%= image_tag card.user.image.url(:thumb), class: "avatar-thumb" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<h1>Users Index</h1>

<p>There are currently <%= @users.length %> users signed up</p>

app/views/users/new.html.erb
<section id='signup-form' class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for @user do |f| %>
        <fieldset>
          <legend>Signup</legend>

          <div class="form-group">
            <label class="col-md-4 control-label" for="first">First name:</label>
            <div class="col-md-8">
              <%= f.text_field :first, required: true, placeholder: "John", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="last">Last name:</label>
            <div class="col-md-8">
              <%= f.text_field :last, required: true, placeholder: "Doe", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email address:</label>
            <div class="col-md-8">
              <%= f.text_field :email, required: true, placeholder: "example@example.com", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password">Password</label>
            <div class="col-md-8">
              <%= f.password_field :password, required: true, placeholder: "Password", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Sign up", class: "btn btn-success" %>
            </div>
          </div>

        </fieldset>
      <% end %>

    </div>
  </div>
</section>

app/views/users/show.html.erb
<!-- render user profile here -->
<div class="container">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= @user.first %> <%= @user.last %>'s profile
			</div>
			<div class="panel-body">
				<div class="col-md-4 profile"> 
					<% if @user.image? %>
						<%= image_tag @user.image.url(:thumb), class: "profile_pic" %> <br> <br>
						<%= link_to 'DELETE PHOTO', delete_photo_path, method: :put, class: "profile_pic" %>
					<% else %>
						<%= image_tag "/assets/default.png", size: "100", class: "profile_pic" %>
					<% end %>
				</div>
				<div class="col-md-7 profile">
				<p class="profile-title">Email:</p> <p class="profile-text">  <%= @user.email %></p>
				<p class="profile-title">Program: </p> <p class="profile-text"> <%= @user.program %> <%= @user.cohort %></p>
				<p class="profile-title">Current Title: </p> <p class="profile-text"> <%= @user.current_title %></p>
				<p class="profile-title">Current City: </p> <p class="profile-text"> <%= @user.city %>, <%= @user.state %></p>
				</div>
			</div>
			<div class="panel-footer">
			<!-- modal button -->
				<%= link_to "Edit Profile", class: 'btn btn-warning', 'data-target' => "#editProfileModal_#{current_user.id}", 'data-toggle' => 'modal' do %><i class="glyphicon glyphicon-pencil"></i> Edit Profile<% end %>
			<!-- new card modal button -->
				<%= link_to "Add new Card", class: 'btn btn-warning pull-right','data-target' => "#newCardModal", 'data-toggle' => 'modal' do %> <i class="glyphicon glyphicon-plus"></i> New Card<% end %>
			</div> 
		</div>
	</div>

 <!-- card container -->
	<div class="col-md-7 col-md-offset-1">
		<% @cards.each do |card| %>
			<div class="card <%= card.family %>">
				<h5 class="flag flag-<%= card.family %> pull-right">
					<% if card.family == "skill_share" %>
						SKILL SHARE
					<% else %>
						<%= card.family.upcase %>
					<% end %>
				</h5>
				<h5 class="title"><%= card.title.upcase %> </h5>
				<!-- left side (user info) -->
				<br>
				<p class="location pull-right"><span class="glyphicon glyphicon-map-marker"></span> <%= card.user.city.upcase %>, <%= card.user.state.upcase %></p>
				<p class="name"><%= card.user.first.upcase %> <%= card.user.last.upcase %></p>
				<p class="current-position"> <%= card.user.current_title %></p>

				<!-- right side (card info) -->
				<p class="profile-title">WORKING ON:</p> <%= card.working_on %>

				<!-- bottom (buttons and timestamp) -->
				<div class="centered">
					<%= link_to edit_card_path(card.id), class: 'btn btn-warning', 'data-target' => "#editCardModal", 'data-toggle' => 'modal' do %><i class="glyphicon glyphicon-pencil"></i><% end %>
					<%= link_to delete_card_path(card.id), method: :delete, class: "btn btn-danger" do  %><i class="glyphicon glyphicon-trash"></i><% end %>
				</div>
			</div>
			<div class="profile-time">Created <%= time_ago_in_words(card.created_at).gsub('about','') %> ago</div>
		<% end %>
	</div>
</div>

<!-- profile modal html -->
<div class="modal fade" id='<%= "editProfileModal_#{current_user.id}" %>' role="dialog" aria-labelledby="editProfileModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="editProfileModalLabel">Edit Profile</h4>
      </div>
      <div class="modal-body">
        <%= render 'users/form', user: current_user %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- edit card modal -->
<div class="modal fade" id='<%= "editCardModal" %>' role="dialog" aria-labelledby="editCardModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newCardModalLabel">Edit Card</h4>
      </div>
      <div class="modal-body">
        <%= render 'cards/editCard' %>		      
      </div>
  		<div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- new card modal html -->
<div class="modal fade" id='<%= "newCardModal" %>' role="dialog" aria-labelledby="newCardModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newCardModalLabel">New Card</h4>
      </div>
      <div class="modal-body">
        <%= render 'cards/newCard' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->